### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ZHUYMGeo** [chenning0115/SpectralDiff#1]
Hello, I am also doing this work, and I am also interested in your work. May I know when to upload the code

**Comment by chenning0115** [comment]
Thank you for your interest in our work. Since we are still in the review period, we have not released all the codes for the time being, but we have established a temporary repo and pushed the code about the diffusion training process. Comments and corrections are welcome. here is the repo link  https://github.com/chenning0115/spectral_diff_temp

**Comment by ZHUYMGeo** [comment]
Thank you for your replay and your work. I think it is better to train diffusion model and classification network in end-to-end fashion.
